monitor=,preferred,auto,1

general {
    gaps_in = 6
    gaps_out = 14
    border_size = 2
    col.active_border = rgba(7aa2f7ee) rgba(9ece6aee) 45deg
    col.inactive_border = rgba(3b4261aa)
    resize_on_border = true
    layout = dwindle
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}
